import React from "react";

const Profile = () => {
  return (
    <div >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt iste ipsa consectetur soluta recusandae sunt optio minus, repudiandae cumque eos non, deleniti natus magni exercitationem perspiciatis atque corrupti laboriosam delectus! Nostrum blanditiis laboriosam eaque exercitationem, ab quis neque quasi dolor repellat soluta. Pariatur vel itaque reprehenderit saepe sit maiores ex exercitationem fugit perspiciatis corporis mollitia accusantium quis dolor, laudantium, vitae fugiat in. Doloribus a quibusdam, nihil voluptate, inventore saepe officiis sequi temporibus porro eius itaque eum non commodi molestias nobis molestiae enim voluptas? Sit quas sint culpa, perferendis fugiat veniam. Consequuntur quibusdam debitis sed veniam aut tempora, repellendus, molestias labore, animi quo commodi eaque placeat fuga vitae suscipit voluptatum dolore hic. Voluptates rem, iste asperiores hic accusamus provident qui quas nulla atque. Itaque assumenda ipsum vero. Nisi impedit necessitatibus minima. Tempore unde neque quaerat tempora, provident sequi doloribus temporibus commodi soluta. Cupiditate maxime ad minima dicta mollitia! Eaque minima voluptas possimus quisquam voluptate veritatis distinctio, laborum repellendus recusandae laudantium beatae ipsum quam eos quidem ipsa odio quod consequuntur? Praesentium accusantium eaque aliquam voluptas magnam, necessitatibus enim perferendis fugit unde sed sunt similique libero, veniam maxime molestias iste architecto at earum deleniti, quisquam amet? Nostrum aperiam distinctio consequuntur tempora saepe beatae dicta et possimus laborum consectetur consequatur laboriosam perspiciatis eaque eius, quidem, voluptas debitis, iure quisquam aspernatur. Soluta similique quia a tempore rem repellat animi pariatur reprehenderit. Odio omnis facere minus doloremque harum rem voluptatibus facilis sit fuga inventore quidem veniam suscipit eaque id qui perferendis ullam quia enim laborum, delectus tenetur eveniet itaque nulla vel! Illum laboriosam dignissimos suscipit sapiente officia praesentium autem amet architecto optio exercitationem, voluptatem quo ut corrupti corporis incidunt pariatur eligendi, ducimus eaque quae. Aliquid repellat necessitatibus deserunt magnam, odio quibusdam cum cumque? Non, hic numquam doloribus aperiam laudantium consectetur magni, labore ipsa placeat rerum rem?</div>
  );
};

export default Profile;
